Repository scapegoat-scala/scapegoat, pull requests merged in 2020-03, with the labels that each got.

#283 Add mergify to label dependency updates from Scala Steward.
  .mergify.yml
Labels: dependency-update

#309 Update sbt-scalafmt to 2.3.2
  project/plugins.sbt
Labels: dependency-update

#314 Update scala-xml to 1.3.0
  build.sbt
Labels: dependency-update

#317 Update sbt-scalafix to 0.9.12
  project/plugins.sbt
Labels: dependency-update

#318 Add github PR action
  .github/workflows/pr-checks.yml
  .travis.yml
  build.sbt
  project/plugins.sbt
  src/main/scala/com/sksamuel/scapegoat/inspections/NoOpOverride.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/exception/CatchException.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/exception/SwallowedException.scala
Labels: chore

#322 Warnings clean up
  src/main/scala/com/sksamuel/scapegoat/Inspection.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/LonelySealedTrait.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/MaxParameters.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/RedundantFinalModifierOnMethod.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/TypeShadowing.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/VariableShadowing.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/MapGetAndGetOrElse.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/PreferSeqEmpty.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseFunc.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverse.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTakeReverse.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/controlflow/RepeatedIfElseBody.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/math/UseExpM1.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/string/InvalidRegex.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/style/ParameterlessMethodReturnsUnit.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/unneccesary/VarCouldBeVal.scala
  src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala
  src/main/scala/com/sksamuel/scapegoat/io/IOUtils.scala
  src/main/scala/com/sksamuel/scapegoat/plugin.scala
  src/test/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeTraversableMethodsTest.scala
Labels: chore

#329 False-positive - empty methods no so empty
  src/main/scala/com/sksamuel/scapegoat/inspections/empty/EmptyMethod.scala
  src/test/scala/com/sksamuel/scapegoat/inspections/empty/EmptyMethodTest.scala
Labels: false positive

#330 Add a description to the AsInstanceOf inspection.
  src/main/scala/com/sksamuel/scapegoat/inspections/math/UseLog1P.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/option/OptionGet.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/unsafe/AsInstanceOf.scala
Labels: minor

#331 Enforcing proper formatting of descriptions and explanations
  src/main/scala/com/sksamuel/scapegoat/inspections/LonelySealedTrait.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptyList.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ComparisonToEmptySet.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ExistsSimplifiableToContains.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotHead.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotHeadOption.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotIsEmpty.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterDotSize.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FilterOptionAndGet.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FindAndNotEqualsNoneReplaceWithExists.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/FindDotIsDefined.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseFunc.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTailReverse.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/ReverseTakeReverse.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/collections/UnsafeContains.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/controlflow/RepeatedIfElseBody.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/math/BigDecimalScaleWithoutRoundingMode.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/math/BrokenOddness.scala
  src/main/scala/com/sksamuel/scapegoat/inspections/unsafe/FinalizerWithoutSuper.scala
  src/main/scala/com/sksamuel/scapegoat/io/HtmlReportWriter.scala
  src/main/scala/com/sksamuel/scapegoat/plugin.scala
  src/test/scala/com/sksamuel/scapegoat/AllInspectionsTest.scala
Labels: chore
